[package]
name = "ip-checker"
version = "1.0.0"
edition = "2024"

[dependencies]
async-signal = "0.2.14"
axum = "0.8.9"
base64 = "0.22.1"
cidr = "0.3.2"
cloneable_errors = "2.3.0"
futures-lite = "2.6.1"
html-escape = "0.2.13"
indexmap = { version = "2.14.0", features = ["serde"] }
reqwest = { version = "0.13.3", default-features = false }
rustls-webpki = "0.103.13"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
tokio = { version = "1.52.2", features = ["rt-multi-thread", "net", "macros", "parking_lot", "io-util"] }
tokio-rustls = "0.26.4"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
webpki-roots = "1.0.7"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
todo = "warn"

[profile.release]
strip = true
lto = "thin"
