name: SonarQube Analysis

on:
  push:
    branches:
      - main
  # pull_request:
  #   types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Solvro_devops-ip-checker_3ad74417-8ea2-4fa4-9907-5b2dfac18550
            -Dsonar.sources=.
            -Dsonar.exclusions=**/build/**,**/dist/**,**/tests/**,**/.terraform/**,**/target/**
